package eqlogtools;

public class SpellNames {
	
	public static String[][] spellNamesBard =
		{{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesCleric =
		{{"", "Lull", "Soothe", "Calm", "Pacify"},
		{"", "Courage", "Center", "Daring", "Bravery", "Armor of Protection", "Valor", "Resolution", "Heroic Bond", "Heroism", "Fortitude", "Aegolism"},
		{"", "Symbol of Transal", "Symbol of Ryltan", "Symbol of Pinzarn", "Symbol of Naltron", "Symbol of Marzin", "Naltron's Mark"},
		{"", "Holy Armor", "Spirit Armor", "Guard", "Armor of Faith", "Shield of Words", "Aegis", "Bulwark of Faith"},
		{"", "Divine Aura", "Divine Barrier"},
		{"", "Endure Fire", "Endure Poison", "Endure Cold", "Endure Disease", "Endure Magic", "Resist Fire", "Resist Poison", "Resist Cold", "Resist Disease", "Resist Magic"},
		{"", "Celestial Healing", "Celestial Elixir"},
		{"", "Reckless Strength", "Frenzied Strength"},
		{"", "Mark of Karn", "Divine Intervention"},
		{"", "Improved Invisibility to Undead"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesDruid =
		{{"", "Snare", "Ensnare", "Bonds of Tunare"},
		{"", "Flame Lick", "Immolate", "Breath of Ro"},
		{"", "Stinging Swarm", "Creeping Crud", "Drones of Doom", "Drifting Death"},
		{"", "Winged Death"},
		{"", "Spirit of Wolf", "Wolf Form", "Greater Wolf Form", "Pack Spirit", "Share Wolf Form", "Form of the Great Wolf", "Form of the Howler", "Form of the Hunter"},
		{"", "Scale of Wolf", "Spirit of Cheetah", "Spirit of Scale"},
		{"", "Shield of Thistles", "Shield of Barbs", "Shield of Brambles", "Shield of Spikes", "Shield of Thorns", "Legacy of Spike", "Shield of Blades", "Legacy of Thorn"},
		{"", "Skin like Wood", "Skin like Rock", "Skin like Steel", "Skin like Diamond", "Skin like Nature", "Natureskin", "Protection of the Glades"},
		{"", "Thistlecoat", "Barbcoat", "Bramblecoat", "Spikecoat", "Thorncoat", "Bladecoat"},
		{"", "Regeneration", "Pack Regeneration", "Chloroplast", "Pack Chloroplast", "Regrowth", "Regrowth of the Grove"},
		{"", "Endure Fire", "Endure Cold", "Endure Disease", "Endure Poison", "Resist Fire", "Endure Magic", "Resist Cold", "Resist Disease", "Resist Posion", "Resist Magic", "Circle of Winter", "Circle of Summer"},
		{"", "Feral Spirit", "Savage Spirit"},
		{"", "Harmony", "Ro's Fiery Sundering", "Fixation of Ro", "Glamour of Tunare"},
		{"", "Invisibility versus Animals", "Improved Superior Camouflage"},
		{"", "Treeform", "Levitate", "Spirit of Oak"},
		{"", "See Invisible", "Mask of the Hunter"},
		{"", "Wrath of Nature"},
		{""}};
	
	public static String[][] spellNamesEnchanter =
		{{"", "Mesmerize", "Enthrall", "Entrance", "Dazzle", "Glamour of Kintaz", "Rapture"},
		{"", "Mesmerization", "Fascination"},
		{"", "Whirl Till You Hurl", "Dyn`s Dizzying Draught", "Largarn's Lamentation"},
		{"", "Color Flux", "Color Shift", "Color Skew", "Color Slant"},
		{"", "Tashan", "Tashani", "Tashania", "Wind of Tashani", "Tashanian", "Wind of Tashanian"},
		{"", "Lull", "Soothe", "Calm", "Pacify", "Wake of Tranquility"},
		{"", "Weaken", "Enfeeblement", "Ebbing Strength", "Feckless Might", "Insipid Weakness", "Incapacitate", "Weakness", "Cripple"},
		{"", "Disempower", "Listless Power"},
		{"", "Suffocating Sphere", "Choke", "Suffocate", "Gasping Embrace", "Asphyxiate", "Torment of Argli"},
		{"", "Languid Pace", "Tepid Deeds", "Shiftless Deeds", "Forlorn Deeds"},
		{"", "Charm", "Beguile", "Cajoling Whispers", "Allure", "Boltran`s Agacerie", "Dictate"},
		{"", "Quickness", "Alacrity", "Celerity", "Swift like the Wind", "Aanya's Quickening", "Augment", "Wonderous Rapidity", "Visions of Grandeur", "Speed of the Shissar"},
		{"", "Minor Shielding", "Lesser Shielding", "Shielding", "Major Shielding", "Greater Shielding", "Arch Shielding", "Shield of the Magi"},
		{"", "Haze", "Mist", "Cloud", "Obscure", "Shade", "Shadow", "Umbra"},
		{"", "Breeze", "Clarity", "Boon of the Clear Mind", "Clarity II", "Gift of Insight", "Gift of Pure Thought", "Gift of Brilliance"},
		{"", "Strengthen", "Berserker Strength", "Rampage", "Berserker Spirit", "Bedlam"},
		{"", "Rune I", "Rune II", "Rune III", "Rune IV", "Rune V", "Endure Magic", "Resist Magic", "Group Resist Magic"},
		{"", "Insight", "Brilliance", "Enlightenment", "Enduring Breath", "Serpent Sight", "Ultravision", "Levitate", "Feedback", "Sympathetic Aura", "Radiant Visage", "Adorning Grace", "Overwhelming Splendor"}};
	
	public static String[][] spellNamesMagician =
		{{"", "Malaise", "Malaisement", "Malosi", "Malosini", "Mala"},
		{"", "Shield of Fire", "Shield of Flame", "Inferno Shield", "Barrier of Combustion", "Shield of Lava", "Boon of Immolation", "Cadeau of Flame", "Aegis of Ro"},
		{"", "Minor Shielding", "Lesser Shielding", "Shielding", "Major Shielding", "Greater Shielding", "Arch Shielding", "Shield of the Magi"},
		{"", "Burnout", "Burnout II", "Burnout III", "Burnout IV"},
		{"", "Expedience", "Velocity"},
		{"", "Phantom Leather", "Phantom Chain", "Phantom Plate", "Phantom Armor"},
		{"", "See Invisible", "Elemental Shield"},
		{"", "Elemental Maelstrom", "Wrath of the Elements"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesMonk =
		{{"", "Resistant Discipline"},
		{"", "Fearless Discipline"},
		{"", "Stonestance Discipline"},
		{"", "Whirlwind Discipline"},
		{"", "Voiddance Discipline"},
		{"", "Innerflame Discipline"},
		{"", "Hundred Fists Discipline"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesNecromancer = 
		{{"", "Clinging Darkness", "Engulfing Darkness", "Dooming Darkness", "Cascading Darkness", "Devouring Darkness", "Torment of Shadows"}, 
		{"", "Heat Blood", "Boil Blood", "Ignite Blood", "Pyrocruor"},
		{"", "Poison Bolt", "Venom of the Snake", "Chilling Embrace", "Envenomed Bolt"},
		{"", "Heart Flutter", "Asystole", "Cessation of Cor"},
		{"", "Leach", "Vampiric Curse", "Bond of Death", "Vexing Mordinia"},
		{"", "Splurt"},
		{"", "Disease Cloud", "Infectious Cloud", "Scourge", "Plague"},
		{"", "Screaming Terror"},
		{"", "Dark Pact", "Allure of Death", "Call of Bones", "Lich", "Demi Lich", "Arch Lich"},
		{"", "Intensify Death", "Augment Death", "Augmentation of Death"},
		{"", "Minor Shielding", "Lesser Shielding", "Shielding", "Major Shielding", "Greater Shielding", "Arch Shielding", "Shield of the Magi"},
		{"", "Breath of the Dead", "Dead Man Floating", "Dead Men Floating"},
		{"", "Harmshield", "Quivering Veil of Xarn"},
		{"", "Endure Cold", "Endure Disease", "Resist Cold", "Resist Disease"},
		{"", "Spirit Armor", "Shieldskin", "Leatherskin", "Steelskin", "Diamondskin", "Manaskin"},
		{"", "Deadeye", "Banshee Aura", "Shadow Sight", "Skin of the Shadow"},
		{"", "Shadow Compact", "Pact of Shadow", "Shadowbond"},
		{"", "Numb the Dead", "Rest the Dead"}};
	
	public static String[][] spellNamesPaladin =
		{{"", "Lull", "Soothe", "Calm", "Pacify"},
		{"", "Courage", "Center", "Daring", "Valor", "Resolution"},
		{"", "Symbol of Transal", "Symbol of Ryltan", "Symbol of Pinzarn", "Symbol of Naltron"},
		{"", "Holy Armor", "Spirit Armor", "Guard", "Armor of Faith", "Shield of Words"},
		{"", "Endure Poison", "Endure Disease"},
		{"", "Reckless Strength", "Frenzied Strength"},
		{"", "Yaulp", "Yaulp II", "Yaulp III", "Yaulp IV"},
		{"", "Invisibility versus Undead"},
		{"", "Divine Aura"},
		{"", "Divine Might"},
		{"", "Divine Favor"},
		{"", "Divine Strength"},
		{"", "Divine Purpose"},
		{"", "Celestial Cleansing"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesRanger =
		{{"", "Snare", "Ensnare"},
		{"", "Flame Lick", "Stinging Swarm", "Immolate", "Drones of Doom"},
		{"", "Lull Animal", "Calm Animal"},
		{"", "Skin like Wood", "Skin like Rock", "Skin like Steel", "Skin like Diamond", "Skin like Nature"},
		{"", "Thistlecoat", "Barbcoat", "Bramblecoat", "Spikecoat", "Thorncoat"},
		{"", "Shield of Thistles", "Shield of Brambles", "Shield of Spikes"},
		{"", "Endure Fire", "Endure Cold", "Resist Fire", "Resist Cold"},
		{"", "Firefist", "Strength of Nature"},
		{"", "Call of the Predator"},
		{"", "Spirit of Wolf", "Wolf Form", "Greater Wolf Form"},
		{"", "Strength of Earth", "Storm Strength"},
		{"", "Call of Sky", "Call of Fire"},
		{"", "Call of Earth"},
		{"", "Chloroplast"},
		{"", "Levitate", "Enduring Breath"},
		{"", "Eyes of the Cat", "Chill Sight"},
		{"", "Panic Animal"},
		{"", ""}};
	
	public static String[][] spellNamesRogue =
		{{"", "Resistant Discipline"},
		{"", "Fearless Discipline"},
		{"", "Counterattack Discipline"},
		{"", "Deadeye Discipline"},
		{"", "Nimble Discipline"},
		{"", "Kinesthetics Discipline"},
		{"", "Blinding Speed Discipline"},
		{"", "Duelist Discipline"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesShadowKnight =
		{{"", "Clinging Darkness", "Engulfing Darkness", "Dooming Darkness", "Cascading Darkness"},
		{"", "Heat Blood", "Boil Blood"},
		{"", "Disease Cloud"},
		{"", "Heart Flutter", "Asystole"},
		{"", "Vampiric Embrace"},
		{"", "Vampiric Curse"},
		{"", "Numb the Dead", "Rest the Dead"},
		{"", "Shadow Vortex", "Shroud of Pain"},
		{"", "Siphon Strength", "Wave of Enfeeblement"},
		{"", "Shroud of Hate"},
		{"", "Endure Cold", "Endure Disease", "Resist Cold"},
		{"", "Invisibility versus Undead", "Breath of the Dead", "Deadeye", "Shadow Sight"},
		{"", "Bobbing Corpse"},
		{"", "Grim Aura"},
		{"", "Banshee Aura"},
		{"", "Shieldskin", "Steelskin", "Diamondskin"},
		{"", "Shroud of Death", "Shroud of Undeath"},
		{"", "Strengthen Death"}};
	
	public static String[][] spellNamesShaman =
		{{"", "Drowsy", "Walking Sleep", "Tagar's Insects", "Togor's Insects", "Turgur's Insects", "Tigir's Insects"},
		{"", "Sicken", "Affliction", "Infectious Cloud", "Scourge", "Plague", "Pox of Bertoxxulous"},
		{"", "Tainted Breath", "Envenomed Breath", "Venom of the Snake", "Envenomed Bolt", "Bane of Nife"},
		{"", "Disempower", "Listless Power", "Incapacitate", "Cripple"},
		{"", "Insidious Fever", "Insidious Malady", "Insidious Decay"},
		{"", "Malaise", "Malaisement", "Malosi", "Malosini", "Malo"},
		{"", "Quickness", "Alacrity", "Celerity"},
		{"", "Spirit of Wolf", "Spirit of Cheetah", "Scale of Wolf", "Spirit of Scale"},
		{"", "Burst of Strength", "Frenzy", "Fury", "Rage", "Voice of the Berserker", "Avatar", "Primal Avatar"},
		{"", "Strengthen", "Spirit Strength", "Raging Strength", "Furious Strength", "Tumultuous Strength", "Strength", "Maniacal Strength", "Talisman of the Rhino"},
		{"", "Feet like Cat", "Spirit of Cat", "Nimble", "Agility", "Deliriously Nimble", "Talisman of the Cat"},
		{"", "Dexterous Aura", "Spirit of Monkey", "Rising Dexterity", "Deftness", "Dexterity", "Mortal Deftness", "Talisman of the Raptor"},
		{"", "Spirit of Bear", "Spirit of Ox", "Health", "Stamina", "Riotous Health", "Talisman of the Brute"},
		{"", "Endure Cold", "Endure Fire", "Endure Disease", "Endure Poison", "Endure Magic", "Resist Cold", "Resist Fire", "Resist Disease", "Resist Poison", "Resist Magic", "Talisman of Jasinth", "Talisman of Shadoo"},
		{"", "Regeneration", "Chloroplast", "Regrowth", "Form of the Great Bear"},
		{"", "Inner Fire", "Talisman of Tnarg", "Talisman of Altuna", "Talisman of Kragg", "Focus of Spirit"},
		{"", "Scale Skin", "Turtle Skin", "Protect", "Shifting Shield", "Guardian", "Shroud of the Spirits"},
		{"", "Spirit of Snake", "Alluring Aura", "Glamour", "Charisma", "Talisman of the Serpent", "Unfailing Reverence", "Ultravision", "Acumen", "Levitate", "Enduring Breath", "Spirit Quickening", "Curse of the Spirits"}};
	
	public static String[][] spellNamesWarrior =
		{{"", "Resistant Discipline"},
		{"", "Fearless Discipline"},
		{"", "Evasive Discipline"},
		{"", "Charge Discipline"},
		{"", "Mighty Strike Discipline"},
		{"", "Defensive Discipline"},
		{"", "Furious Discipline"},
		{"", "Precision Discipline"},
		{"", "Felstrike Discipline"},
		{"", "Fortitude Discipline"},
		{"", "Aggressive Discipline"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
	
	public static String[][] spellNamesWizard =
		{{"", "Bonds of Force", "Atol's Spectral Shackles"},
		{"", "Tishan's Clash", "Markar's Clash", "Tishan's Discord", "Thunderbold", "Markar's Discord"},
		{"", "Minor Shielding", "Lesser Shielding", "Shielding", "Major Shielding", "Greater Shielding", "Arch Shielding", "Shield of the Magi"},
		{"", "Shieldskin", "Leatherskin", "Steelskin", "Diamondskin", "Manaskin", "Barrier of Force"},
		{"", "Manasink"},
		{"", "O'Keils Flickering Flame"},
		{"", "Resistant Skin", "Elemental Shield", "Elemental Armor"},
		{"", "Eye of Zomm", "Eye of Tallon"},
		{"", "Improved Invisibility"},
		{"", "Levitate"},
		{"", "See Invisible", "Chill Sight", "Shifting Sight", "Plainsight", "Heat Sight"},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""},
		{"", ""}};
}
