package eqlogtools;

public class StringTrigger {
	
	public static String[][] stringTriggerBard = 
		  {{"NULL_IS_NOT_USED", "", "", "", "", ""}, 
		  {"NULL_IS_NOT_USED", "", "", "", ""},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerCleric = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[0][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[0][2] + ".", "You begin casting " + SpellNames.spellNamesCleric[0][3] + ".", "You begin casting " + SpellNames.spellNamesCleric[0][4] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[1][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][2] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][3] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][4] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][5] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][6] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][7] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][8] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][9] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][10] + ".", "You begin casting " + SpellNames.spellNamesCleric[1][11] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[2][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[2][2] + ".", "You begin casting " + SpellNames.spellNamesCleric[2][3] + ".", "You begin casting " + SpellNames.spellNamesCleric[2][4] + ".", "You begin casting " + SpellNames.spellNamesCleric[2][5] + ".", "You begin casting " + SpellNames.spellNamesCleric[2][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[3][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][2] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][3] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][4] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][5] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][6] + ".", "You begin casting " + SpellNames.spellNamesCleric[3][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[4][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[4][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[5][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][2] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][3] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][4] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][5] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][6] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][7] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][8] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][9] + ".", "You begin casting " + SpellNames.spellNamesCleric[5][10] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[6][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[6][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[7][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[7][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[8][1] + ".", "You begin casting " + SpellNames.spellNamesCleric[8][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesCleric[9][1] + "."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerDruid = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[0][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[0][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[0][3] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[1][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[1][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[1][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[2][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[2][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[2][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[2][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[3][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[4][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][6] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][7] + ".", "You begin casting " + SpellNames.spellNamesDruid[4][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[5][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[5][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[5][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[6][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][6] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][7] + ".", "You begin casting " + SpellNames.spellNamesDruid[6][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[7][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][6] + ".", "You begin casting " + SpellNames.spellNamesDruid[7][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[8][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[8][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[8][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[8][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[8][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[8][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[9][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[9][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[9][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[9][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[9][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[9][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[10][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][4] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][5] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][6] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][7] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][8] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][9] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][10] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][11] + ".", "You begin casting " + SpellNames.spellNamesDruid[10][12] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[11][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[11][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[12][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[12][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[12][3] + ".", "You begin casting " + SpellNames.spellNamesDruid[12][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[13][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[13][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[14][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[14][2] + ".", "You begin casting " + SpellNames.spellNamesDruid[14][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[15][1] + ".", "You begin casting " + SpellNames.spellNamesDruid[15][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesDruid[16][1] + "."},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerEnchanter = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[0][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[0][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[0][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[0][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[0][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[0][6] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[1][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[1][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[2][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[2][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[2][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[3][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[3][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[3][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[3][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[4][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[4][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[4][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[4][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[4][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[4][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[5][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[5][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[5][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[5][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[5][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[6][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][7] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[6][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[7][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[7][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[8][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[8][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[8][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[8][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[8][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[8][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[9][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[9][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[9][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[9][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[10][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[10][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[10][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[10][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[10][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[10][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[11][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][7] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][8] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[11][9] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[12][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[12][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[13][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[13][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[14][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[14][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[15][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[15][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[15][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[15][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[15][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[16][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][7] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[16][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesEnchanter[17][1] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][2] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][3] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][4] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][5] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][6] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][7] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][8] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][9] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][10] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][11] + ".", "You begin casting " + SpellNames.spellNamesEnchanter[17][12] + "."}};
	
	public static String[][] stringTriggerMagician = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[0][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[0][2] + ".", "You begin casting " + SpellNames.spellNamesMagician[0][3] + ".", "You begin casting " + SpellNames.spellNamesMagician[0][4] + ".", "You begin casting " + SpellNames.spellNamesMagician[0][5] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[1][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][2] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][3] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][4] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][5] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][6] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][7] + ".", "You begin casting " + SpellNames.spellNamesMagician[1][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[2][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][2] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][3] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][4] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][5] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][6] + ".", "You begin casting " + SpellNames.spellNamesMagician[2][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[3][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[3][2] + ".", "You begin casting " + SpellNames.spellNamesMagician[3][3] + ".", "You begin casting " + SpellNames.spellNamesMagician[3][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[4][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[4][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[5][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[5][2] + ".", "You begin casting " + SpellNames.spellNamesMagician[5][3] + ".", "You begin casting " + SpellNames.spellNamesMagician[5][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[6][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[6][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesMagician[7][1] + ".", "You begin casting " + SpellNames.spellNamesMagician[7][2] + "."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerMonk = 
		  {{"NULL_IS_NOT_USED", "You channel your will into magical resistance."}, 
		  {"NULL_IS_NOT_USED", "Your will drives fear from your mind."},
		  {"NULL_IS_NOT_USED", "Your body becomes one with the earth."},
		  {"NULL_IS_NOT_USED", "Your instincts take over as you turn aside every attack."},
		  {"NULL_IS_NOT_USED", "You become untouchable."},
		  {"NULL_IS_NOT_USED", "Your muscles bulge with the force of will."},
		  {"NULL_IS_NOT_USED", "Your fists begin to blur."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerNecromancer = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[0][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[0][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[0][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[0][4] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[0][5] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[0][6] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[1][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[1][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[1][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[1][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[2][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[2][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[2][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[2][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[3][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[3][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[3][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[4][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[4][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[4][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[4][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[5][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[6][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[6][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[6][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[6][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[7][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[8][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[8][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[8][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[8][4] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[8][5] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[8][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[9][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[9][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[9][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[10][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][4] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][5] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][6] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[10][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[11][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[11][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[11][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[12][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[12][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[13][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[13][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[13][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[13][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[14][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[14][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[14][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[14][4] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[14][5] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[14][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[15][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[15][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[15][3] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[15][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[16][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[16][2] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[16][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesNecromancer[17][1] + ".", "You begin casting " + SpellNames.spellNamesNecromancer[17][2] + "."}};
	
	public static String[][] stringTriggerPaladin = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[0][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[0][2] + ".", "You begin casting " + SpellNames.spellNamesPaladin[0][3] + ".", "You begin casting " + SpellNames.spellNamesPaladin[0][4] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[1][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[1][2] + ".", "You begin casting " + SpellNames.spellNamesPaladin[1][3] + ".", "You begin casting " + SpellNames.spellNamesPaladin[1][4] + ".", "You begin casting " + SpellNames.spellNamesPaladin[1][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[2][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[2][2] + ".", "You begin casting " + SpellNames.spellNamesPaladin[2][3] + ".", "You begin casting " + SpellNames.spellNamesPaladin[2][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[3][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[3][2] + ".", "You begin casting " + SpellNames.spellNamesPaladin[3][3] + ".", "You begin casting " + SpellNames.spellNamesPaladin[3][4] + ".", "You begin casting " + SpellNames.spellNamesPaladin[3][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[4][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[4][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[5][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[5][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[6][1] + ".", "You begin casting " + SpellNames.spellNamesPaladin[6][2] + ".", "You begin casting " + SpellNames.spellNamesPaladin[6][3] + ".", "You begin casting " + SpellNames.spellNamesPaladin[6][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[7][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[8][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[9][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[10][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[11][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[12][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesPaladin[13][1] + "."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerRanger = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[0][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[0][2] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[1][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[1][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[1][3] + ".", "You begin casting " + SpellNames.spellNamesRanger[1][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[2][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[2][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[3][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[3][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[3][3] + ".", "You begin casting " + SpellNames.spellNamesRanger[3][4] + ".", "You begin casting " + SpellNames.spellNamesRanger[3][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[4][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[4][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[4][3] + ".", "You begin casting " + SpellNames.spellNamesRanger[4][4] + ".", "You begin casting " + SpellNames.spellNamesRanger[4][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[5][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[5][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[5][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[6][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[6][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[6][3] + ".", "You begin casting " + SpellNames.spellNamesRanger[6][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[7][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[7][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[8][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[9][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[9][2] + ".", "You begin casting " + SpellNames.spellNamesRanger[9][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[10][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[10][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[11][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[11][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[12][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[13][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[14][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[14][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[15][1] + ".", "You begin casting " + SpellNames.spellNamesRanger[15][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesRanger[16][1] + "."},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerRogue = 
		  {{"NULL_IS_NOT_USED", "You channel your will into magical resistance."}, 
		  {"NULL_IS_NOT_USED", "Your will drives fear from your mind."},
		  {"NULL_IS_NOT_USED", "Your weapons move with uncanny grace."},
		  {"NULL_IS_NOT_USED", "You feel unstoppable."},
		  {"NULL_IS_NOT_USED", "You bounce about nimbly."},
		  {"NULL_IS_NOT_USED", "Your arms feel alive with mystic energy."},
		  {"NULL_IS_NOT_USED", "Your hands speeds up."},
		  {"NULL_IS_NOT_USED", "Your muscles quiver with power."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerShadowKnight = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[0][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[0][2] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[0][3] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[0][4] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[1][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[1][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[2][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[3][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[3][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[4][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[5][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[6][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[6][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[7][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[7][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[8][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[8][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[9][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[10][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[10][2] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[10][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[11][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[11][2] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[11][3] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[11][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[12][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[13][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[14][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[15][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[15][2] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[15][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[16][1] + ".", "You begin casting " + SpellNames.spellNamesShadowKnight[16][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShadowKnight[17][1] + "."}};
	
	public static String[][] stringTriggerShaman = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[0][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[0][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[0][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[0][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[0][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[0][6] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[1][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[1][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[1][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[1][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[1][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[1][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[2][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[2][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[2][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[2][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[2][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[3][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[3][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[3][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[3][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[4][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[4][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[4][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[5][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[5][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[5][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[5][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[5][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[6][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[6][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[6][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[7][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[7][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[7][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[7][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[8][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][6] + ".", "You begin casting " + SpellNames.spellNamesShaman[8][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[9][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][6] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][7] + ".", "You begin casting " + SpellNames.spellNamesShaman[9][8] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[10][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[10][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[10][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[10][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[10][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[10][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[11][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][6] + ".", "You begin casting " + SpellNames.spellNamesShaman[11][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[12][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[12][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[12][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[12][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[12][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[12][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[13][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][6] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][7] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][8] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][9] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][10] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][11] + ".", "You begin casting " + SpellNames.spellNamesShaman[13][12] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[14][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[14][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[14][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[14][4] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[15][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[15][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[15][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[15][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[15][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[16][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[16][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[16][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[16][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[16][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[16][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesShaman[17][1] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][2] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][3] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][4] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][5] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][6] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][7] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][8] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][9] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][10] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][11] + ".", "You begin casting " + SpellNames.spellNamesShaman[17][12] + "."}};
	
	public static String[][] stringTriggerWarrior = 
		  {{"NULL_IS_NOT_USED", "You channel your will into magical resistance."}, 
		  {"NULL_IS_NOT_USED", "Your will drives fear from your mind."},
		  {"NULL_IS_NOT_USED", "You assume an evasive fighting style."},
		  {"NULL_IS_NOT_USED", "Your focus becomes perfect."},
		  {"NULL_IS_NOT_USED", "You feel like a killing machine."},
		  {"NULL_IS_NOT_USED", "You assume a defensive fighting style."},
		  {"NULL_IS_NOT_USED", "A consuming rage takes over your weapons."},
		  {"NULL_IS_NOT_USED", "Your attacks take on deadly precision."},
		  {"NULL_IS_NOT_USED", "Your weapons strike true."},
		  {"NULL_IS_NOT_USED", "You instincts take over as you avoid every attack."},
		  {"NULL_IS_NOT_USED", "You assume an aggressive fighting style."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
	
	public static String[][] stringTriggerWizard = 
		  {{"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[0][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[0][2] + "."}, 
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[1][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[1][2] + ".", "You begin casting " + SpellNames.spellNamesWizard[1][3] + ".", "You begin casting " + SpellNames.spellNamesWizard[1][4] + ".", "You begin casting " + SpellNames.spellNamesWizard[1][5] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[2][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][2] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][3] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][4] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][5] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][6] + ".", "You begin casting " + SpellNames.spellNamesWizard[2][7] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[3][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[3][2] + ".", "You begin casting " + SpellNames.spellNamesWizard[3][3] + ".", "You begin casting " + SpellNames.spellNamesWizard[3][4] + ".", "You begin casting " + SpellNames.spellNamesWizard[3][5] + ".", "You begin casting " + SpellNames.spellNamesWizard[3][6] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[4][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[5][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[6][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[6][2] + ".", "You begin casting " + SpellNames.spellNamesWizard[6][3] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[7][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[7][2] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[8][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[9][1] + "."},
		  {"NULL_IS_NOT_USED", "You begin casting " + SpellNames.spellNamesWizard[10][1] + ".", "You begin casting " + SpellNames.spellNamesWizard[10][2] + ".", "You begin casting " + SpellNames.spellNamesWizard[10][3] + ".", "You begin casting " + SpellNames.spellNamesWizard[10][4] + ".", "You begin casting " + SpellNames.spellNamesWizard[10][5] + "."},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"},
		  {"NULL_IS_NOT_USED"}};
}
